os: linux
language: shell
services: docker
install: sudo apt-get -y install jq sed curl

env:
  global:
    - REPO=${DOCKER_USERNAME}/nordvpn
  jobs:
    - ARCH=amd64
    - ARCH=armv7hf
  
before_script: 
  - DOCKER_VERSION=$(curl -sSL "https://registry.hub.docker.com/v2/repositories/$REPO/tags?page_size=1024" | jq -r '."results"[]["name"]' | grep '^[0-9].*[0-9]$' | sort | uniq | tail -n 1)
  - NORDVPN_VERSION=$(curl https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/ | grep amd64.deb | sed 's/\(<a.*nordvpn_\)\([0-9.-]\+\).*/\2/' | sort | uniq | tail -n 1)
  - if [ "${TRAVIS_EVENT_TYPE}" == "cron" ] && [ "${NORDVPN_VERSION}" == "${DOCKER_VERSION}" ]; then exit 0 ; fi
  - VERSION="${NORDVPN_VERSION}" ; BRANCH="latest"
  - if [ "${TRAVIS_BRANCH}" != "master" ]; then VERSION+="${TRAVIS_BRANCH}" ; BRANCH="${TRAVIS_BRANCH}" ; fi   
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "${ARCH}" == "armv7hf" ]; then sed -i 's/^#CROSSRUN/RUN/g' Dockerfile ; fi

stage: "Build"
script:
  - docker build --build-arg ARCH=${ARCH} --build-arg NORDVPN_VERSION=${NORDVPN_VERSION} -t $REPO:${ARCH}-${VERSION} .
  - docker push $REPO:${ARCH}-${VERSION}
  - docker tag $REPO:${ARCH}-${VERSION} $REPO:${ARCH}-${BRANCH}
  - docker push $REPO:${ARCH}-${BRANCH}
  
jobs:
  fast_finish: true
  include:
    - stage: "Deploy"
      name: "Manifest"
      git:
        clone: false
      script:
        - cat <<< $(jq '.+{"experimental":"enabled"}' ~/.docker/config.json) > ~/.docker/config.json
        - | 
          push() {
            docker pull $REPO:amd64-${1}
            docker pull $REPO:armv7hf-${1}
            docker manifest create $REPO:${1} $REPO:amd64-${1} $REPO:armv7hf-${1}
            docker manifest annotate $REPO:${1} $REPO:amd64-${1} --os linux --arch amd64
            docker manifest annotate $REPO:${1} $REPO:armv7hf-${1} --os linux --arch arm --variant v7
            docker manifest push --purge $REPO:${1}
          }
        - push ${VERSION}
        - push ${BRANCH}
